### ISSUE TITLE
Log skipped scenarios as ignored in team city

### ISSUE THREAD

**Issue by kevinkuszyk** [bingnz/cucumber-teamcity-formatter#2]
I noticed that `skipped` scenarios are showing as passed.  Would you take a PR to show those as ignored instead?

**Comment by bingnz** [comment]
Yes, pull requests are gratefully accepted :) Next time I'm in the area that uses this I can possibly take a look as well.

**Comment by bingnz** [comment]
Fixed in https://github.com/bingnz/cucumber-teamcity-formatter/pull/4.
